config/routes.rb
Rails.application.routes.draw do
  resources :memes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
class Meme < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.all
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, notice: 'Meme was successfully created.' }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :edit }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meme_params
      params.fetch(:meme, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitHelp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_with(model: meme, local: true) do |form| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memes/edit.html.erb
<h1>Editing Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

app/views/memes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memes.each do |meme| %>
      <tr>
        <td><%= link_to 'Show', meme %></td>
        <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
        <td><%= link_to 'Destroy', meme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meme', new_meme_path %>

app/views/memes/new.html.erb
<h1>New Meme</h1>

<%= render 'form', meme: @meme %>

<%= link_to 'Back', memes_path %>

app/views/memes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>